plugins {
  id 'java'
  id 'org.jetbrains.kotlin.jvm' version '1.8.21'
  id 'io.qameta.allure' version '2.9.3'
}

group 'com.example'
version '1.0-SNAPSHOT'

repositories {
  mavenCentral()
}

ext {
  allureVersion = '2.22.0'
}

sourceCompatibility = '20'
targetCompatibility = '19'

tasks.withType(JavaCompile) {
  options.encoding = 'UTF-8'
}

[compileKotlin, compileTestKotlin].forEach {
  it.kotlinOptions {
        jvmTarget = '19'
  }
}

sourceSets {
  main {
    java {
      srcDirs = ['src/main/kotlin']
    }
  }
}

dependencies {
  implementation('org.testng:testng:6.6.1')
  implementation("io.qameta.allure:allure-selenide:${allureVersion}")
  implementation('org.slf4j:slf4j-simple:2.0.7')
  implementation 'io.appium:java-client:8.1.1'
  implementation 'org.seleniumhq.selenium:selenium-java:4.2.1'
  implementation('org.testng:testng:7.7.1')
}

test {
useTestNG()}
allure {
  autoconfigure = true
  version = "${allureVersion}"

useTestNG {
    version = "${allureVersion}"
  }}