plugins {
  id("java")
  id("org.jetbrains.kotlin.jvm") version "2.3.10"
  id("io.qameta.allure") version "3.0.2"
}

group 'com.example'
version '1.0-SNAPSHOT'

repositories {
  mavenCentral()
}

ext {
  allureVersion = '2.33.0'
}

java {
  sourceCompatibility = JavaVersion.VERSION_25
  targetCompatibility = JavaVersion.VERSION_25
}

kotlin {
  jvmToolchain(25)
}

tasks.withType(JavaCompile).configureEach {
  options.encoding = 'UTF-8'
}

sourceSets {
  main {
    java {
      srcDirs = ['src/main/kotlin']
    }
  }
}

dependencies {
  implementation('org.testng:testng:6.6.1')
  implementation("io.qameta.allure:allure-selenide:${allureVersion}")
  implementation('org.slf4j:slf4j-simple:2.0.7')
  implementation 'io.appium:java-client:9.4.0'
  implementation 'org.seleniumhq.selenium:selenium-java:4.2.1'
  implementation('org.testng:testng:7.7.1')
}

test {
  useTestNG()
}
allure {
  version = "${allureVersion}"

useTestNG {
    version = "${allureVersion}"
  }
}